#!/usr/bin/env bash
# ============================================================
# Zero-Knowledge Vault — Unified Audit Script
# Runs all local security/quality checks and produces a single
# Markdown report consumable by humans or AI reviewers.
#
# Usage:
#   bun run audit:full
#   ./scripts/audit.sh
#
# Output:
#   ./audit-reports/<timestamp>.md  — full audit report
#   ./audit-reports/latest.md      — symlink to latest
# ============================================================

set -uo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

REPORT_DIR="$PROJECT_ROOT/audit-reports"
mkdir -p "$REPORT_DIR"

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
REPORT="$REPORT_DIR/audit-$TIMESTAMP.md"
SARIF_DIR="$REPORT_DIR/sarif-$TIMESTAMP"
mkdir -p "$SARIF_DIR"

# ----- Helpers -----
section() {
  echo ""
  echo "## $1" >> "$REPORT"
  echo "" >> "$REPORT"
}

code_block() {
  echo '```' >> "$REPORT"
  echo "$1" >> "$REPORT"
  echo '```' >> "$REPORT"
  echo "" >> "$REPORT"
}

run() {
  local label="$1"
  shift
  local out
  out="$("$@" 2>&1)" || true
  section "$label"
  code_block "$out"
}

# ----- Header -----
cat > "$REPORT" <<EOF
# Zero-Knowledge Vault — Audit Report

- **Generated:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
- **Commit:** $(git rev-parse HEAD 2>/dev/null || echo "n/a")
- **Branch:** $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "n/a")
- **Node:** $(node -v 2>/dev/null || echo "n/a")
- **Bun:** $(bun -v 2>/dev/null || echo "n/a")

This report is auto-generated by \`scripts/audit.sh\`. It bundles the output of every
local analyzer into a single Markdown document so that any reviewer (human or AI)
can audit the codebase in one pass.

EOF

echo "▶ Starting audit. Report: $REPORT"

# ----- 1. Dependency manifest -----
section "1. Dependency Manifest"
{
  echo "Total dependencies: $(jq '.dependencies | length' package.json 2>/dev/null || echo '?')"
  echo "Total devDependencies: $(jq '.devDependencies | length' package.json 2>/dev/null || echo '?')"
  echo ""
  echo "### Production dependencies"
  jq -r '.dependencies | to_entries | map("  - \(.key)@\(.value)") | .[]' package.json 2>/dev/null
  echo ""
  echo "### devDependencies"
  jq -r '.devDependencies | to_entries | map("  - \(.key)@\(.value)") | .[]' package.json 2>/dev/null
} >> "$REPORT"
echo "" >> "$REPORT"

# ----- 2. Lockfile stats -----
section "2. Lockfile Statistics"
{
  if [ -f bun.lock ]; then
    echo "bun.lock size: $(du -h bun.lock | cut -f1)"
    echo "Resolved packages (approx): $(jq '.packages | length' bun.lock 2>/dev/null || echo '?')"
  fi
} >> "$REPORT"
echo "" >> "$REPORT"

# ----- 3. Bun audit -----
echo "▶ bun audit"
run "3. bun audit (production)" bun audit --production --severity moderate

# ----- 4. ESLint security -----
echo "▶ eslint"
section "4. ESLint (security + no-unsanitized)"
ESLINT_OUT="$(bunx eslint . --format compact 2>&1 || true)"
code_block "$ESLINT_OUT"
WARN_COUNT="$(echo "$ESLINT_OUT" | grep -c -E '\bwarning\b' || true)"
ERR_COUNT="$(echo "$ESLINT_OUT" | grep -c -E '\berror\b' || true)"
echo "" >> "$REPORT"
echo "**ESLint summary:** $ERR_COUNT errors, $WARN_COUNT warnings" >> "$REPORT"
echo "" >> "$REPORT"

# ----- 5. TypeScript typecheck -----
echo "▶ tsc --noEmit"
run "5. TypeScript typecheck (tsc --noEmit)" bunx tsc --noEmit

# ----- 6. Semgrep -----
echo "▶ semgrep"
if command -v semgrep >/dev/null 2>&1; then
  SEMGREP_OUT="$(semgrep --config=semgrep.yml --json --output "$SARIF_DIR/semgrep.json" . 2>&1 || true)"
  section "6. Semgrep SAST"
  code_block "$SEMGREP_OUT"
  if [ -f "$SARIF_DIR/semgrep.json" ]; then
    FINDINGS="$(jq '.results | length' "$SARIF_DIR/semgrep.json" 2>/dev/null || echo '?')"
    ERRORS="$(jq '[.results[] | select(.extra.severity=="ERROR")] | length' "$SARIF_DIR/semgrep.json" 2>/dev/null || echo '?')"
    WARNINGS="$(jq '[.results[] | select(.extra.severity=="WARNING")] | length' "$SARIF_DIR/semgrep.json" 2>/dev/null || echo '?')"
    echo "" >> "$REPORT"
    echo "**Semgrep summary:** $FINDINGS findings ($ERRORS errors, $WARNINGS warnings)" >> "$REPORT"
  fi
else
  section "6. Semgrep SAST"
  code_block "semgrep not installed. Install with: pip install semgrep"
fi

# ----- 7. Cyclomatic complexity (complexity-report) -----
echo "▶ complexity-report"
section "7. Cyclomatic Complexity"
if bunx --bun ts-prune > /dev/null 2>&1; then
  TS_PRUNE_OUT="$(bunx ts-prune 2>&1 | head -50 || true)"
  echo "### ts-prune (unused exports)" >> "$REPORT"
  code_block "$TS_PRUNE_OUT"
fi

# Use eslint with complexity rule as fallback
COMPLEXITY_OUT="$(bunx eslint . --rule '{"complexity": ["warn", {"max": 15}]}' --format=json 2>/dev/null | jq '[.[] | .. | .messages? // empty | objects | select(.ruleId=="complexity")] | length' 2>/dev/null || echo '?')"
echo "" >> "$REPORT"
echo "### Functions exceeding cyclomatic complexity > 15" >> "$REPORT"
echo "" >> "$REPORT"
bunx eslint . --rule '{"complexity": ["warn", {"max": 15}]}' --format=compact 2>&1 | grep "complexity" | head -50 >> "$REPORT" || true
echo "" >> "$REPORT"
echo "**Functions with complexity > 15:** $COMPLEXITY_OUT" >> "$REPORT"
echo "" >> "$REPORT"

# ----- 8. Dead code detection -----
echo "▶ ts-prune"
run "8. Dead code (ts-prune)" bunx --bun ts-prune 2>/dev/null

# ----- 9. License compliance -----
echo "▶ license-checker"
section "9. License compliance"
{
  npx --yes license-checker --production --summary 2>&1 || true
} >> "$REPORT"
echo "" >> "$REPORT"

# ----- 10. Source line counts -----
section "10. Source Code Statistics"
{
  echo "### Lines of code by directory"
  for d in src/lib src/app/api src/components scripts prisma; do
    if [ -d "$d" ]; then
      count="$(find "$d" -type f \( -name '*.ts' -o -name '*.tsx' -o -name '*.prisma' \) -exec cat {} + | wc -l)"
      printf "  - %-30s %8d LOC\n" "$d" "$count"
    fi
  done
  echo ""
  echo "### Top 20 largest source files"
  find src scripts -type f \( -name '*.ts' -o -name '*.tsx' \) -exec wc -l {} + 2>/dev/null \
    | sort -rn | head -20
} >> "$REPORT"
echo "" >> "$REPORT"

# ----- 11. Type-coverage -----
echo "▶ type-coverage"
run "11. Type coverage (type-coverage)" bunx --bun type-coverage

# ----- 12. Prisma schema validation -----
echo "▶ prisma validate"
run "12. Prisma schema validation" bunx prisma validate --schema prisma/schema.prisma

# ----- 13. Crypto audit (custom heuristic) -----
section "13. Crypto Implementation Audit"
{
  echo "### Web Crypto API usage"
  echo ""
  echo '| API | Count | Files |'
  echo '|-----|-------|-------|'
  for api in "crypto.subtle.encrypt" "crypto.subtle.decrypt" "crypto.subtle.deriveKey" "crypto.subtle.deriveBits" "crypto.subtle.generateKey" "crypto.subtle.importKey" "crypto.subtle.exportKey" "crypto.subtle.sign" "crypto.subtle.verify" "crypto.subtle.wrapKey" "crypto.subtle.unwrapKey" "crypto.getRandomValues"; do
    count=$(grep -rn "$api" src/ 2>/dev/null | wc -l || echo 0)
    files=$(grep -rln "$api" src/ 2>/dev/null | wc -l || echo 0)
    printf '| `%s` | %s | %s |\n' "$api" "$count" "$files"
  done
  echo ""
  echo "### Insecure crypto (should all be 0)"
  echo ""
  echo '| Pattern | Count |'
  echo '|---------|-------|'
  for pat in "Math.random" "createHash('md5'" "createHash(\"md5\"" "createHash('sha1'" "AES-CBC" "AES-ECB" "DES" "RC4" "Math\.random\(\)"; do
    count=$(grep -rEn "$pat" src/ 2>/dev/null | wc -l || echo 0)
    printf '| `%s` | %s |\n' "$pat" "$count"
  done
  echo ""
  echo "### Zeroization calls"
  echo ""
  echo '| Function | Count |'
  echo '|----------|-------|'
  for fn in "clearCryptoKeyRef" "clearKeyPairRef" "zeroBuffer" "crypto.subtle.digest"; do
    count=$(grep -rn "$fn" src/ 2>/dev/null | wc -l || echo 0)
    printf '| `%s` | %s |\n' "$fn" "$count"
  done
} >> "$REPORT"
echo "" >> "$REPORT"

# ----- 14. Endpoint inventory -----
section "14. API Endpoint Inventory"
{
  echo '| Method | Path | File |'
  echo '|--------|------|------|'
  find src/app/api -name "route.ts" | sort | while read -r f; do
    rel="${f#src/app/api/}"
    route="/${rel%/route.ts}"
    methods=""
    for m in GET POST PUT DELETE PATCH; do
      if grep -q "export async function $m\b" "$f" 2>/dev/null; then
        methods="${methods:+$methods,}$m"
      fi
    done
    printf '| %s | `%s` | %s |\n' "${methods:-?}" "$route" "$f"
  done
} >> "$REPORT"
echo "" >> "$REPORT"

# ----- 15. ZK-specific audit (master key flow) -----
section "15. Zero-Knowledge Property Audit"
{
  echo "### Files referencing master password"
  grep -rln "masterPassword\|password" src/lib/crypto-client.ts src/app/api/auth 2>/dev/null | sort
  echo ""
  echo "### Server-side references to plaintext secrets (must be 0)"
  echo '```'
  grep -rEn "masterPassword|plaintextSecret|unencryptedSecret" src/app/api/ 2>/dev/null | grep -v "test\|spec\|example" || echo "(none found — OK)"
  echo '```'
  echo ""
  echo "### Files that import crypto-client"
  grep -rln "from.*crypto-client" src/ 2>/dev/null | sort
} >> "$REPORT"
echo "" >> "$REPORT"

# ----- 16. SBOM generation (CycloneDX) -----
echo "▶ cyclonedx-bom"
section "16. SBOM (CycloneDX)"
if bunx --bun cyclonedx-bom -o "$SARIF_DIR/sbom.cdx.json" --spec-version 1.5 2>&1 | head -20; then
  echo '```json'
  head -50 "$SARIF_DIR/sbom.cdx.json" 2>/dev/null
  echo '```'
else
  code_block "cyclonedx-bom not available. Install: bun add -d @cyclonedx/cyclonedx-bom"
fi

# ----- 17. Git history hygiene -----
section "17. Git History Hygiene"
{
  echo '```'
  echo "Total commits: $(git rev-list --count HEAD 2>/dev/null)"
  echo "Latest 10 commits:"
  git log --oneline -10 2>/dev/null
  echo ""
  echo "Commits with AI-mention keywords (should be 0):"
  git log --oneline -E -i --grep="AI|Z\.ai|scaffold|generated by|co-authored by" 2>/dev/null | head -20 || echo "(none — OK)"
  echo '```'
} >> "$REPORT"
echo "" >> "$REPORT"

# ----- 18. Markdown docs audit -----
section "18. Documentation Files"
{
  echo '| File | Size | Lines |'
  echo '|------|------|-------|'
  find . -maxdepth 3 -name "*.md" -not -path "./node_modules/*" -not -path "./.next/*" -not -path "./skills/*" -not -path "./audit-reports/*" 2>/dev/null | sort | while read -r f; do
    size=$(du -h "$f" | cut -f1)
    lines=$(wc -l < "$f")
    printf '| %s | %s | %s |\n' "$f" "$size" "$lines"
  done
} >> "$REPORT"
echo "" >> "$REPORT"

# ----- Summary -----
section "Summary"
{
  echo "Audit completed at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo ""
  echo "Next steps for reviewer:"
  echo "1. Read AUDITING.md for the step-by-step audit methodology."
  echo "2. Read SECURITY_CHECKLIST.md for the 100+ point verification list."
  echo "3. Use the prompt in docs/AI_AUDIT_PROMPT.md to feed this report + source to any LLM."
  echo "4. Cross-check findings against CI results in the Actions tab."
} >> "$REPORT"

# ----- Finalize -----
ln -sf "audit-$TIMESTAMP.md" "$REPORT_DIR/latest.md"

echo ""
echo "✓ Audit complete."
echo "  Report: $REPORT"
echo "  Latest: $REPORT_DIR/latest.md"
echo "  SARIF:  $SARIF_DIR/"
